[[main]]
name = "Articles"
url = "/posts/"
weight = 10

[[main]]
name = "Legacy"
url = "/legacy/"
weight = 20

[[main]]
name = "Search"
url = "/search/"
weight = 30

[[main]]
name = "Tags"
url = "/tags/"
weight = 40

[[main]]
name = "About"
url = "/about/"
weight = 50